# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'
  
# Unused variables
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Install Node
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

# Install Angular dependencies
- script: npm install 
  workingDirectory: Frontend/general-frontend
  displayName: Install Angular packages

# Build Angular
- script: npm run build -- --configuration test
  workingDirectory: Frontend/general-frontend
  displayName: Build Angular packages

# Copy Angular dist to wwwroot
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Frontend/general-frontend/dist/general-frontend'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/Backend/src/1-Presentation/GeneralWebApi.WebApi/wwwroot'
    OverWrite: true

# Install .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'

# Restore .NET dependencies
- script: dotnet restore Backend/GeneralWebApi.sln
  displayName: Restore .NET packages

# Publish
- script: dotnet publish Backend/src/1-Presentation/GeneralWebApi.WebApi/GeneralWebApi.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: Publish .NET